# Generated by Django 3.1.5 on 2021-02-21 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_cate', models.CharField(max_length=30)),
                ('c_star', models.BooleanField(default=False)),
                ('c_diary', models.BooleanField(default=False)),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['c_user', '-c_id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_content', models.CharField(max_length=200)),
                ('s_startDate', models.DateField(null=True)),
                ('s_endDate', models.DateField(null=True)),
                ('s_red', models.BooleanField(default=False)),
                ('s_busy', models.CharField(choices=[('0', ''), ('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★')], default='0', max_length=1)),
                ('s_complete', models.BooleanField(default=False)),
                ('s_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.category')),
                ('s_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['s_cate', '-s_id'],
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_title', models.CharField(max_length=100)),
                ('d_content', models.TextField()),
                ('d_date', models.DateField()),
                ('d_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.category')),
                ('d_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['d_cate', '-d_id'],
            },
        ),
    ]
