# Generated by Django 3.1.5 on 2021-02-21 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_reject', models.BooleanField(default=False)),
                ('p_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.category')),
                ('p_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yourname', to=settings.AUTH_USER_MODEL)),
                ('p_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.category')),
                ('f_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
                ('f_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['f_user', 'f_id'],
            },
        ),
    ]
